---
name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
env:
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1
  ANSIBLE_STDOUT_CALLBACK: yaml
jobs:
  lint:
    if: ${{ !contains(github.head.ref, 'dependabot') }}
    runs-on: ubuntu-latest
    container: leandelivery/docker-ansible-ci:ansible-2.9
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install yamllint # till https://github.com/lean-delivery/docker-ansible-ci/pull/22 is not resolved
        run: apk add --update yamllint
      - name: Lints
        run: |
          git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
          yamllint . -c .yamllint
          ansible-lint . -c .ansible-lint

  molecule:
    needs: lint
    strategy:
      matrix:
        scenario:
          - default
        distro:
          - centos8
          - centos7
          - fedora34
          - fedora33
          - amazonlinux2
          - ubuntu2004
          - ubuntu1804
          - ubuntu1604
          - ubuntu1404
          - debian10
          - debian9
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install test dependencies.
        run: pip3 install ansible==2.9.* molecule[docker] docker
      - name: Prepare
        run: | 
          ansible --version
          ansible-lint --version
          molecule --version
          pip install jmespath
      - name: Molecule
        run: molecule test -s ${{ matrix.scenario }}
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
